# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1
  owasp: entur/owasp@0.0.15
  sonarqube: clicklogiq/sonarqube@1.0.1

workflows:
  sample:
    jobs:
      - owasp/commandline_owasp_dependency_check
      - sonarqube/analyze 
#      - node/test:
#          version: '15.1'
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
