version: '2.1'
orbs:
  deepfactor: deepfactor/deepfactor@1.2.0
workflows:
  build:
    jobs:
      - deepfactor/scan:
          app-name: circleci-demo-job
          cmd: /usr/local/bin/npm test
          component-name: circleci-demo-javascript-express
          portal-url: 'https://portswigger.net/web-security'
          pre-run:
            - checkout
            - run:
                command: dfctl version
                name: Deep Factor CLI Version
            - run:
                command: sudo npm install
                name: update-npm
          tag: circleci-build
  version: 2.1