version: '2.1'
orbs:
  deepfactor: deepfactor/deepfactor@1.2.0
workflows:
  build:
    jobs:
      - deepfactor/scan:
          app-name: circleci-demo-job
          cmd: /usr/local/bin/npm test
          component-name: circleci-demo-javascript-express
          portal-url: 'https://portswigger.net/web-security'
          pre-run:
            - checkout
            - run:
                command: |
                  echo 'export DF_RUN_TOKEN=b5efb76f4a48f748b70a7285c6aff767cd7a2c27' >> $BASH_ENV
                  source $BASH_ENV
                  echo "DF_RUN_TOKEN=" $DF_RUN_TOKEN
                  echo "Just for fun!"
                  echo "CIRCLE_BUILD_NUM = "${CIRCLE_BUILD_NUM}
                name: Deep Factor CLI Version
            - run:
                command: |
                  sudo apt update
                  sudo apt install npm
                name: update-npm
            - run:
                command: |
                  #echo "ls /usr/lib/node_modules/"
                  #ls /usr/lib/node_modules/
                  #echo "node --version"
                  #node --version
                  echo "npm --version"
                  npm --version
                  echo "npm root -g"
                  npm root -g
                  #dfctl run -v -a circleci-demo-job -c circleci-demo-javascript-express --version "${CIRCLE_BUILD_NUM}" --cmd /usr/lib/node_modules/npm test
                name: Deep Factor Failed Command
          tag: circleci-build
  version: 2.1