version: '2.1'
orbs:
  deepfactor: deepfactor/deepfactor@1.2.0
workflows:
  build:
    jobs:
      - deepfactor/scan:
          app-name: circleci-demo-job
          cmd: /usr/local/bin/npm test
          component-name: circleci-demo-javascript-express
          portal-url: 'https://portswigger.net/web-security'
          pre-run:
            - checkout
            - run:
                command: |
                  echo 'export DF_RUN_TOKEN=b5efb76f4a48f748b70a7285c6aff767cd7a2c27 >> $BASH_ENV
                  source $BASH_ENV
                  echo $DF_RUN_TOKEN
                name: Deep Factor CLI Version
            - run:
                command: sudo apt install nodejs
                name: update-npm
          tag: circleci-build
  version: 2.1