version: 2.1

orbs:
  owasp: entur/owasp@0.0.15

jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      #- setup_remote_docker
      - checkout
      - run:
          name: Zap Scanning
          command: |
            sudo chmod ugo+rwx /home/circleci/project
            ls -l /home/circleci && echo "Full Access Granted"
            (
              docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py \
              -t http://www.itsecgames.com/ -d -r testreport.html || \
              if [ $? -ne 1 ]; then exit 0; else exit 1; fi; 
            )
            # cat testreport.html
      - store_artifacts:
          path: testreport.html

workflows:
  owasp_dependency_check:
    jobs:
      - owasp/commandline_owasp_dependency_check