# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  owasp: entur/owasp@0.0.15
  sonarqube: clicklogiq/sonarqube@1.0.1

workflows:
  sample:
    jobs:
      - owasp/commandline_owasp_dependency_check
      - sonarqube/analyze